paths:
  data: D:\Learning\NLP\Projects\EssayInsightAI\analyzer\data  
  tokenizer: D:\Learning\NLP\Projects\EssayInsightAI\analyzer\models\distilbert-base-uncased
  model: D:\Learning\NLP\Projects\EssayInsightAI\analyzer\models\distilbert-base-uncased
data:
  max_len: 512
  val_split: 0.1
train_ds:
  batch_size: 4
  shuffle: True
  num_workers: 2
  pin_memory: True
test_ds:
  batch_size: 2
  shuffle: False
  num_workers: 2
  pin_memory: True
model:
training:
  lr: 0.00002
  epochs: 2