paths:
  data: D:\Learning\NLP\Projects\EssayInsightAI\analyzer\data  
  tokenizer: D:\Learning\NLP\Projects\EssayInsightAI\analyzer\models\distilbert-base-uncased
  model: D:\Learning\NLP\Projects\EssayInsightAI\analyzer\models\distilbert-base-uncased
seed: 2024
data:
  max_len: 512
  val_split: 0.1
  strategy: stratifiedkfold
  num_folds: 2
train_ds:
  batch_size: 2
  shuffle: True
  num_workers: 2
  pin_memory: True
test_ds:
  batch_size: 2
  shuffle: False
  num_workers: 2
  pin_memory: True
model:
training:
  lr: 0.00002
  epochs: 10
postprocess:
  models:
    - D:\Learning\NLP\Projects\EssayInsightAI\analyzer\output\distilbert\train_val\lightning_logs\version_0\checkpoints\epoch=9-step=50.ckpt
    - D:\Learning\NLP\Projects\EssayInsightAI\analyzer\output\distilbert\kfold_1\lightning_logs\version_0\checkpoints\epoch=2-step=9.ckpt
    # - D:\Learning\NLP\Projects\EssayInsightAI\analyzer\output\distilbert\kfold_2\lightning_logs\version_0\checkpoints\epoch=2-step=9.ckpt
    # - D:\Learning\NLP\Projects\EssayInsightAI\analyzer\output\distilbert\stratifiedkfold_1\lightning_logs\version_0\checkpoints\epoch=2-step=9.ckpt
    # - D:\Learning\NLP\Projects\EssayInsightAI\analyzer\output\distilbert\stratifiedkfold_2\lightning_logs\version_0\checkpoints\epoch=1-step=6.ckpt
  operations:
    # - soft_ensemble
    - hard_ensemble
    - bound_average