paths:
  data: D:\Learning\NLP\Projects\EssayInsightAI\analyzer\data  
  tokenizer: D:\Learning\NLP\Projects\EssayInsightAI\analyzer\models\bert-large-uncased
  model: D:\Learning\NLP\Projects\EssayInsightAI\analyzer\models\bert-large-uncased
seed: 2024
data:
  max_len: 512
  val_split: 0.1
  strategy: train_val
  num_folds: 2
train_ds:
  batch_size: 2
  shuffle: True
  num_workers: 2
  pin_memory: True
test_ds:
  batch_size: 2
  shuffle: False
  num_workers: 2
  pin_memory: True
model:
training:
  lr: 0.00002
  epochs: 5
postprocess:
  models:
    # - D:\Learning\NLP\Projects\EssayInsightAI\analyzer\output\distilbert_uncased\kfold_1\lightning_logs\version_0\checkpoints\epoch=9-step=3900.ckpt
    - D:\Learning\NLP\Projects\EssayInsightAI\analyzer\output\bert_large_uncased\train_val\lightning_logs\version_0\checkpoints\epoch=6-step=12278.ckpt
  operations:
    # - soft_ensemble
    - hard_ensemble
    - bound_average